config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :friends
  resources :homes do
    collection do
      get :about 
    end
  end
  root 'homes#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friend.rb
class Friend < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: %i[show edit update destroy]

  # GET /friends or /friends.json
  def index
    @friends = Friend.all
  end

  # GET /friends/1 or /friends/1.json
  def show; end

  # GET /friends/new
  def new
    @friend = Friend.new
  end

  # GET /friends/1/edit
  def edit; end

  # POST /friends or /friends.json
  def create
    @friend = Friend.new(friend_params)

    respond_to do |format|
      if @friend.save
        format.html { redirect_to @friend, notice: 'Friend was successfully created.' }
        format.json { render :show, status: :created, location: @friend }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friends/1 or /friends/1.json
  def update
    respond_to do |format|
      if @friend.update(friend_params)
        format.html { redirect_to @friend, notice: 'Friend was successfully updated.' }
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends/1 or /friends/1.json
  def destroy
    @friend.destroy
    respond_to do |format|
      format.html { redirect_to friends_url, notice: 'Friend was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_friend
    @friend = Friend.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def friend_params
    params.require(:friend).permit(:first_name, :last_name, :email, :phone, :twitter, :gender, department: [])
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/list_helper.rb
module ListHelper
end

app/views/friends/_form.html.haml
= form_with(model: friend) do |form|
  - if friend.errors.any?
    #error_explanation
      %h2
        = pluralize(friend.errors.count, "error")
        prohibited this friend from being saved:
      %ul
        - friend.errors.each do |error|
          %li= error.full_message
  .field.form-group
    = form.label :first_name
    = form.text_field :first_name, class:"form-control"
  .field.form-group
    = form.label :last_name
    = form.text_field :last_name, class:"form-control"
  .field.form-group
    = form.label :email
    = form.text_field :email, class:"form-control"
  .field.form-group
    = form.label :phone
    = form.text_field :phone, class:"form-control"
  .field.form-group
    = form.label :twitter
    = form.text_field :twitter, class:"form-control"
  %br/
  .field.form-group
    = form.check_box :department, { multiple: true}, 'developer', nil
    = form.label :department, "Developer"
    = form.check_box :department, {multiple: true }, 'admin', nil
    = form.label :department, "Admin"
  %br/
  .field.form-group
    = form.radio_button :gender, "Male"
    = form.label :gender_male, "Male"
    = form.radio_button :gender, "Female"
    = form.label :gender_female, "Female"
    = form.radio_button :gender, "Prefer Not to Say"
    = form.label :gender_others, "Prefer Not to Say"
  %br/
  .actions.form-group
    = form.submit class:"btn btn-secondary"
  %br/

app/views/friends/edit.html.haml
%h1 Editing Friend
= render 'form', friend: @friend
= link_to 'Show', @friend,  class: "btn btn-secondary"
= link_to 'Back', friends_path,  class: "btn btn-secondary"

app/views/friends/index.html.haml
%table.table.table-striped.table-hover
  %thead.table-dark
    %tr
      %th First name
      %th Last name
      %th Email
      %th Phone
      %th Twitter
      %th Department
      %th Gender
      %th{:colspan => "3"}
  %tbody
    - @friends.each do |friend|
      %tr
        %td= friend.first_name
        %td= friend.last_name
        %td= friend.email
        %td= friend.phone
        %td= friend.twitter
        %td= friend.department
        %td= friend.gender
        %td= link_to 'Show', friend
        %td= link_to 'Edit', edit_friend_path(friend)
        %td= link_to 'Destroy', friend, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'Add New Friend', new_friend_path, class: "btn btn-secondary"
= params.inspect

app/views/friends/new.html.haml
%h1 Add New Friend
= render 'form', friend: @friend
= link_to 'Back', friends_path, class: "btn btn-secondary"

app/views/friends/show.html.haml
%p
  %strong First name:
  = @friend.first_name
%p
  %strong Last name:
  = @friend.last_name
%p
  %strong Email:
  = @friend.email
%p
  %strong Phone:
  = @friend.phone
%p
  %strong Twitter:
  = @friend.twitter
%p
  %strong Department:
  = @friend.department
%p
  %strong Gender:
  = @friend.gender
= link_to 'Edit', edit_friend_path(@friend),  class: "btn btn-secondary"
= link_to 'Back', friends_path,  class: "btn btn-secondary"

app/views/homes/_header.html.haml
/ This is for the Partial Header File - use _filename.html.erb
%nav.navbar.navbar-expand-lg.navbar-dark.bg-dark
  .container-fluid
    = link_to 'Friends App', root_path, class: "navbar-brand"
    %button.navbar-toggler{"aria-controls" => "navbarSupportedContent", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-bs-target" => "#navbarSupportedContent", "data-bs-toggle" => "collapse", :type => "button"}
      %span.navbar-toggler-icon
    #navbarSupportedContent.collapse.navbar-collapse
      %ul.navbar-nav.me-auto.mb-2.mb-lg-0
        %li.nav-item
          = link_to 'Add Friend' , new_friend_path, class:"nav-link"
        %li.nav-item
          = link_to 'My Friends' , friends_path, class:"nav-link"
        %li.nav-item
          = link_to 'About Us' , about_homes_path, class:"nav-link"
      %form.d-flex
        %input.form-control.me-2{"aria-label" => "Search", :placeholder => "Search", :type => "search"}/
        %button.btn.btn-outline-success{:type => "submit"} Search

app/views/homes/about.html.haml
%h1 Resources Refered
%h5 https://guides.rubyonrails.org/form_helpers.html
%h5 https://guides.rubyonrails.org/active_record_migrations.html

app/views/homes/index.html.haml
%h1 Homes#index
%p Find me in app/views/homes/index.html.erb

app/views/layouts/_alerts.html.haml
.alert.alert-warning.alert-dismissible.fade.show{:role => "alert"}
  = notice
  %button.btn-close{"aria-label" => "Close", "data-bs-dismiss" => "alert", :type => "button"}

app/views/layouts/application.html.haml
!!!
%html{:lang => "en"}
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    / Required meta tags
    %meta{:charset => "utf-8"}/
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    / Bootstrap CSS
    %link{:crossorigin => "anonymous", :href => "https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css", :integrity => "sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl", :rel => "stylesheet"}/
    %title Friends App
  %body
    %header
      / Navigation Bar inside Header. Header is _header.html.erb partial file.
      = render 'homes/header'
    %br/
    - if notice
      = render 'layouts/alerts'
    .container
      = yield
    / Optional JavaScript; choose one of the two!
    / Option 1: Bootstrap Bundle with Popper
    %script{:crossorigin => "anonymous", :integrity => "sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0", :src => "https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js"}
    / Option 2: Separate Popper and Bootstrap JS
    /
      <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.6.0/dist/umd/popper.min.js" integrity="sha384-KsvD1yqQ1/1+IA7gi3P0tyJcT3vR+NdBTt13hSJ2lnve8agRGXTTyNaBYmCR/Nwi" crossorigin="anonymous"></script>
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.min.js" integrity="sha384-nsg8ua9HAw1y0W1btsyWgBklPnCUAFLuTMS2G72MMONqmOymq585AcH49TLBQObG" crossorigin="anonymous"></script>